### ISSUE TITLE
Rule are not applied to ConfigMap if namespace=debug

### ISSUE THREAD

**Issue by timansky** [opsgy/loki-rule-operator#5]
Rule are not applied to ConfigMap if namespace selector in expression equals debug

Ex:
```
spec:
  groups:
    - name: Loki
       rules:
        - alert: test_alert
          expr: sum(rate({namespace="debug",service="blabla"}[1m])) > 0
          for: 5m
            alert_type: loki_test
          annotations:
            summary: "Debug message"
```
