### ISSUE TITLE
Support record rule type

### ISSUE THREAD

**Issue by timansky** [opsgy/loki-rule-operator#8]
In loki v2.3.0 was announced support of ruller record metrics
```
name: NginxRules
interval: 1m
rules:
  - record: nginx:requests:rate1m
    expr: |
      sum(
        rate({container="nginx"}[1m])
      )
    labels:
      cluster: "us-central1"
```

current release does not support this rule type
